- name: "ICARUS_NuMI_1muNp0pi_selection"
  isEnabled: true
  selectedDataEntry: "FakeDataFromMC"
  showSelectedEventCount: true

  mc:
    tree: "events/full/selected"
    filePathList:
      - "/exp/icarus/data/users/rvizarr/medulla/icarus_numi_numu_mc_onbeam_offbeam_syst_gundam_withPCA.root"
    nominalWeightFormula: "((ppfx_cv_weight) * (2.36124e+19/7.78521e+20))" #2.21627e+19/1.471115e+20
  data:
    # data from the same MC
    - name: "FakeDataFromMC"
      tree: "events/onbeam/selected"
      nominalWeightFormula: "(1.0)"
      filePathList:
      - "/exp/icarus/data/users/rvizarr/medulla/icarus_numi_numu_mc_onbeam_offbeam_syst_gundam_withPCA.root"

- name: "ICARUS_NuMI_1muNp0pi_sideband"
  isEnabled: true
  selectedDataEntry: "FakeDataFromMC_sideband"
  showSelectedEventCount: true

  mc:
    tree: "events/full/sideband"
    filePathList:
      - "/exp/icarus/data/users/rvizarr/medulla/icarus_numi_numu_mc_onbeam_offbeam_syst_gundam_withPCA.root"
    nominalWeightFormula: "((ppfx_cv_weight) * (2.36124e+19/7.78521e+20))" #2.21627e+19/1.471115e+20
  data:
    # data from the same MC
    - name: "FakeDataFromMC_sideband"
      tree: "events/onbeam/sideband"
      nominalWeightFormula: "(1.0)"
      filePathList:
      - "/exp/icarus/data/users/rvizarr/medulla/icarus_numi_numu_mc_onbeam_offbeam_syst_gundam_withPCA.root"
