- name: "ICARUS_NuMI_1muNp0pi_selection"
  isEnabled: true
  selectedDataEntry: "FakeDataFromMC"
  showSelectedEventCount: true

  mc:
    tree: "events/full/selected"
    filePathList:
      - "/exp/icarus/data/users/rvizarr/medulla/icarus_numi_numu_mc_onbeam_offbeam_syst_gundam.root"
    nominalWeightFormula: "(ppfx_cv_weight)"
  data:
    # data from the same MC
    - name: "FakeDataFromMC"
      #tree: "events/full/selected" # For Asimov fake data
      tree: "events/onbeam/selected" # For real data
      #nominalWeightFormula: "(ppfx_cv_weight)" # For Asimov fake data
      nominalWeightFormula: "(1.0)" # For real data
      filePathList:
      - "/exp/icarus/data/users/rvizarr/medulla/icarus_numi_numu_mc_onbeam_offbeam_syst_gundam.root"

- name: "ICARUS_NuMI_1muNp0pi_sideband"
  isEnabled: true
  selectedDataEntry: "FakeDataFromMC_sideband"
  showSelectedEventCount: true

  mc:
    tree: "events/full/sideband"
    filePathList:
      - "/exp/icarus/data/users/rvizarr/medulla/icarus_numi_numu_mc_onbeam_offbeam_syst_gundam.root"
    nominalWeightFormula: "(ppfx_cv_weight)"
  data:
    # data from the same MC
    - name: "FakeDataFromMC_sideband"
      #tree: "events/full/sideband" # For Asimov fake data
      tree: "events/onbeam/sideband" # For real data
      #nominalWeightFormula: "(ppfx_cv_weight)" # For Asimov fake data
      nominalWeightFormula: "(1.0)" # For real data
      filePathList:
      - "/exp/icarus/data/users/rvizarr/medulla/icarus_numi_numu_mc_onbeam_offbeam_syst_gundam.root"
