- parameterName: "hysyst_beam_horn_2kA"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_beam_horn_2kA"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_beam_horn1_x_3mm"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_beam_horn1_x_3mm"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_beam_horn1_y_3mm"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_beam_horn1_y_3mm"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_beam_spot_1_3mm"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_beam_spot_1_3mm"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_beam_spot_1_7mm"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_beam_spot_1_7mm"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_beam_horn2_x_3mm"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_beam_horn2_x_3mm"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_beam_horn2_y_3mm"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_beam_horn2_y_3mm"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_beam_horns_0mm_water"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_beam_horns_0mm_water"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_beam_horns_2mm_water"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_beam_horns_2mm_water"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_beam_Beam_shift_x_1mm"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_beam_Beam_shift_x_1mm"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_beam_Beam_shift_y_1mm"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_beam_Beam_shift_y_1mm"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_beam_Target_z_7mm"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_beam_Target_z_7mm"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_hpc_0"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_hpc_0"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_hpc_1"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_hpc_1"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_hpc_2"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_hpc_2"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_hpc_3"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_hpc_3"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_hpc_4"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_hpc_4"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_hpc_5"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_hpc_5"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_hpc_6"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_hpc_6"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_hpc_7"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_hpc_7"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_hpc_8"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_hpc_8"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_hpc_9"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_hpc_9"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_hpc_10"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_hpc_10"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_hpc_11"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_hpc_11"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_hpc_12"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_hpc_12"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_hpc_13"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_hpc_13"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
- parameterName: "hysyst_hpc_14"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minDialResponse: 0
      maxDialResponse: 10
      dialLeafName: "hysyst_hpc_14"
      applyOnDataSets: ["ICARUS_NuMI_1muNp0pi_selection", "ICARUS_NuMI_1muNp0pi_sideband"]
      applyCondition: "[is_nu]==1"
