- parameterName: "GENIEReWeight_SBN_v1_multisigma_ZExpA1CCQE"
  isEnabled: false
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_ZExpA1CCQE"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_ZExpA2CCQE"
  isEnabled: false
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_ZExpA2CCQE"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_ZExpA3CCQE"
  isEnabled: false
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_ZExpA3CCQE"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_ZExpA4CCQE"
  isEnabled: false
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_ZExpA4CCQE"
      applyCondition: "[is_nu]==1"

- parameterName: "ZExpPCAWeighter_myreweighter_b1"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "ZExpPCAWeighter_myreweighter_b1"
      applyCondition: "[is_nu]==1"

- parameterName: "ZExpPCAWeighter_myreweighter_b2"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "ZExpPCAWeighter_myreweighter_b2"
      applyCondition: "[is_nu]==1"

- parameterName: "ZExpPCAWeighter_myreweighter_b3"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "ZExpPCAWeighter_myreweighter_b3"
      applyCondition: "[is_nu]==1"

- parameterName: "ZExpPCAWeighter_myreweighter_b4"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "ZExpPCAWeighter_myreweighter_b4"
      applyCondition: "[is_nu]==1"
#
#- parameterName: "Synthetic_multisigma_NormCCRES"
#  isEnabled: true
#  dialSetDefinitions:
#    - dialType: Spline
#      minimumSplineResponse: 0
#      dialLeafName: "Synthetic_multisigma_NormCCRES"
#      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_RPA_CCQE"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_RPA_CCQE"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_CoulombCCQE"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_CoulombCCQE"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NormCCMEC"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NormCCMEC"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NormNCMEC"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NormNCMEC"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_MaNCEL"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_MaNCEL"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_EtaNCEL"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_EtaNCEL"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_MaCCRES"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_MaCCRES"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_MvCCRES"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_MvCCRES"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_MaNCRES"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_MaNCRES"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_MvNCRES"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_MvNCRES"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvpCC1pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvpCC1pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvpCC2pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvpCC2pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvpNC1pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvpNC1pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvpNC2pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvpNC2pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvnCC1pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvnCC1pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvnCC2pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvnCC2pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvnNC1pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvnNC1pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvnNC2pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvnNC2pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarpCC1pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarpCC1pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarpCC2pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarpCC2pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarpNC1pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarpNC1pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarpNC2pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarpNC2pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarnCC1pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarnCC1pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarnCC2pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarnCC2pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarnNC1pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarnNC1pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarnNC2pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NonRESBGvbarnNC2pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_RDecBR1gamma"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_RDecBR1gamma"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_RDecBR1eta"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_RDecBR1eta"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NormCCCOH"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NormCCCOH"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_NormNCCOH"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_NormNCCOH"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_AhtBY"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_AhtBY"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_BhtBY"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_BhtBY"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_CV1uBY"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_CV1uBY"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_CV2uBY"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_CV2uBY"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_MFP_pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_MFP_pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_FrCEx_pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_FrCEx_pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_FrInel_pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_FrInel_pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_FrAbs_pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_FrAbs_pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_FrPiProd_pi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_FrPiProd_pi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_MFP_N"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_MFP_N"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_FrCEx_N"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_FrCEx_N"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_FrInel_N"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_FrInel_N"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_FrAbs_N"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_FrAbs_N"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_FrPiProd_N"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_FrPiProd_N"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_CC1piTPi"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_CC1piTPi"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_LowQ2Suppression"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_LowQ2Suppression"
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_VecFFCCQEshape"
  isEnabled: true
#  isFixed: true
  priorValue: 0
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_VecFFCCQEshape"
      useMirrorDial: true
      mirrorLowEdge: -1
      mirrorHighEdge: 1
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_DecayAngMEC"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_DecayAngMEC"
      useMirrorDial: true
      mirrorLowEdge: -1
      mirrorHighEdge: 1
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_Theta_Delta2Npi"
  isEnabled: true
  isFixed: true
  priorValue: 0
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_Theta_Delta2Npi"
      useMirrorDial: true
      mirrorLowEdge: -1
      mirrorHighEdge: 1
      applyCondition: "[is_nu]==1"

- parameterName: "GENIEReWeight_SBN_v1_multisigma_ThetaDelta2NRad"
  isEnabled: true
  dialSetDefinitions:
    - dialType: Spline
      minimumSplineResponse: 0
      dialLeafName: "GENIEReWeight_SBN_v1_multisigma_ThetaDelta2NRad"
      useMirrorDial: true
      mirrorLowEdge: -1
      mirrorHighEdge: 1
      applyCondition: "[is_nu]==1"

