varDictionnaries:
  - name: "category"
    dictionary:
      # Signal category (types 0 and 3)
      - { value: 0, title: "Signal", color: 418 }
      - { value: 3, title: "Signal", color: 418 }
      - { value: 1, title: "Signal", color: 416 }
      - { value: 4, title: "Signal", color: 416 }

      # Other CC category (types 6, 7, 8)
      - { value: 6, title: "Other CC", color: 807 }
      - { value: 7, title: "Other CC", color: 807 }
      - { value: 8, title: "Other CC", color: 807 }

      # ν NC category (type 9)
      - { value: 9, title: "$\nu$ NC", color: 632 }

      # OOFV category (types 2 and 5)
      - { value: 2, title: "OOFV", color: 797 }
      - { value: 5, title: "OOFV", color: 797 }

      # Cosmic category (type 10)
      - { value: 10, title: "Cosmic", color: 880 }

histogramsDefinition:
  - varToPlot: "reco_dpT_lp"
    splitVars: ["category"]
    useSampleBinning: true
    rescaleAsBinWidth: true
    xTitle: "#deltap_{T} (MeV/c)"
    yTitle: "Slices"
    xMax: 1200

canvasParameters:
  height: 800
  width: 1000
  nbXplots: 1
  nbYplots: 1
