varDictionnaries:
  - name: "category"
    dictionary:
      # Signal category (types 0 and 3)
      - { value: 0, title: "Signal", color: 418 }


histogramsDefinition:
  - varToPlot: "reco_dpT"
    splitVars: ["category"]
    useSampleBinning: true
    rescaleAsBinWidth: false
    xTitle: "#deltap_{T} (GeV/c)"
    yTitle: "Slices"
    xMax: 3.2

canvasParameters:
  height: 800
  width: 1000
  nbXplots: 1
  nbYplots: 1
