name: G4 Piplus Fate (contained)
isEnabled: true

printDialSetsSummary: true

allowPca: true
useEigenDecompInFit: true
allowEigenDecompWithBounds: true

covarianceMatrixFilePath: "${GUNDAM_CONFIG_DIR}/Configs_ParameterSet/G4/outputs/output_CovMat_G4Piplus_contained.root"
covarianceMatrixTMatrixD: "G4Piplus_contained/G4Piplus_contained_covariance"

parameterLimits:
  minValue: 0
  maxValue: 30

useOnlyOneParameterPerEvent: true

dialSetDefinitions:
  - name: G4 Piplus Fate (contained) dialSetDefinitions
    applyOnDataSets: ["*"]
    parametersBinningPath: "${GUNDAM_CONFIG_DIR}/binnings/binning_reco_dpT_contained.txt"
    printDialsSummary: true
    applyCondition: "([is_nu]==1) && ([reco_leading_muon_containment]==1)"
