name: Template Parameter true_leading_muon_cos_theta_mu
isEnabled: true

printDialSetsSummary: true

nominalStepSize: 0.1
useOnlyOneParameterPerEvent: true

dialSetDefinitions:
  - name: Template Parameter true_leading_muon_cos_theta_mu  dialSetDefinitions
    # 'applyOnDataSets' can take a list or a wildcard
    applyOnDataSets: ["*"]
    parametersBinningPath: "${GUNDAM_CONFIG_DIR}/binnings/binning_true_muon_angle.txt"
    applyCondition: "([category]==0) || ([category]==1) || ([category]==2)"
    printDialsSummary: true

parameterLimits:
  minValue: 0.
  maxValue: 3.0
