fitSampleList:
  - name: "signal_DeltaPT"
    isEnabled: true
    binning: "${GUNDAM_CONFIG_DIR}/binnings/binning_DeltaPT.txt"
    selectionCuts: "category==0 || category==1 || category==3 || category==4"
    dataSets: ["ICARUS_NuMI_1muNp0pi"]
