fitSampleList:
  - name: "True_dpT_XS"
    isEnabled: true
    binning: "${GUNDAM_CONFIG_DIR}/binnings/binning_true_dpT.txt"

    selectionCuts: ""

    dataSets: ["ICARUS_NuMI_1muNp0pi_signal"]
    parameterSetName: "Template Parameter true_dpT_lp_genie"
    yAxis: "#frac{d #sigma}{d #delta p_{T}} #frac{cm^{2}}{(MeV/c)Ar}"
    normaliseParameterList:
      - name: "Constant flux"
        isEnabled: true

        #meanValue: 1.076331e+11  # (numu+numubar)/cm², POT = 1.47e20
        meanValue: 1.63e+10  # (numu+numubar)/cm², POT = 2.22e19
        stdDev: 1.436e+9 #1.436e+10     # 12.59% uncertainty

      - name: "Number of targets"
        meanValue: 4.721444e+30
        stdDev: 9.4281120e+27
