fitSampleList:
  - name: "signal_dalphaT_deg"
    isEnabled: true
    binning: "${GUNDAM_CONFIG_DIR}/binnings/binning_reco_dalphaT_deg.txt"
    selectionCuts: "cut_type==1"
    dataSets: ["ICARUS_NuMI_1muNp0pi"]
  - name: "sideband_reco_dalphaT"
    isEnabled: true
    binning: "${GUNDAM_CONFIG_DIR}/binnings/binning_reco_dalphaT_deg.txt"
    selectionCuts: "cut_type==1"
    dataSets: ["ICARUS_NuMI_1muNp0pi_sideband"]