fitSampleList:
  - name: "signal_muonP"
    isEnabled: true
    binning: "${GUNDAM_CONFIG_DIR}/binnings/binning_muonP.txt"
    selectionCuts: "(category==0) || (category==1) || (category==3) || (category==4)"
    dataSets: ["ICARUS_NuMI_1muNp0pi"]
