fitSampleList:
  - name: "signal_dpT"
    isEnabled: true
    binning: "${GUNDAM_CONFIG_DIR}/binnings/binning_reco_dpT.txt"
    selectionCuts: "cut_type==1"
    dataSets: ["ICARUS_NuMI_1muNp0pi"]
  - name: "sideband_reco_dpT"
    isEnabled: true
    binning: "${GUNDAM_CONFIG_DIR}/binnings/binning_reco_dpT.txt"
    selectionCuts: "cut_type==1"
    dataSets: ["ICARUS_NuMI_1muNp0pi"]
